# Definición de la API de Kubernetes para Servicios
apiVersion: v1
kind: Service
metadata:
  # Nombre del servicio que se usará para la resolución de DNS interno
  name: bonos-service
  namespace: default
  labels:
    app: bonos-service
spec:
  # Mapeo de puertos
  ports:
    - port: 8004
      targetPort: 8004
      name: http
  # Selector para encontrar qué pods pertenecen a este servicio
  selector:
    app: bonos-service
  # Tipo de servicio: ClusterIP (solo accesible internamente en el clúster)
  type: ClusterIP
